### ISSUE TITLE
Intro lecture

### ISSUE THREAD

**Issue by willirath** [mardatade/Course-Software-Testing#1]
@fp21 The PDF looks like a great base for the lecture-like intro part! Do you need assistance in the translation? (We could split this and then review each other's parts.)

Also, we've added time to the testing slot so that now there's a (max) 1.5h session for a lecture-like intro that should be based on the existing slides and another (max.) 1.5h session that immediately follows for a hands-on part. (We can adjust the times and go for a longer hands-on part or for a longer break if we like.)

**Comment by fp21** [comment]
Hi, i wanted to use the slides as a base structure for the lecture part. So I would translate them in the process. If think we could also translate them first and then build the new slides.

Who should do the lecture part? I suggest that we split the part up.

As an idea for the base structure:

Testing - What for?
What is testing?
Common methods / SE Methods
Automated Test
Oracle Test/ Lookup check
Unit Test
Integration Testing
Metamorphic  Testing
Transition to hands-on part

**Comment by willirath** [comment]
> Who should do the lecture part? I suggest that we split the part up.

I'm fine with splitting this up. As I'm quite used to doing these kinds of tutorials and lectures, I would be okay with just being the fall-back person who presents whichever parts you or @dilipjh leave over. So feel free to pick anywhere between 0% and 100% of the lecture part for you to present and I'll take care of the rest.

**Comment by willirath** [comment]
> Testing - What for?
> What is testing?

In the upper two points, it's important to make sure that this is mostly about testing as part of the development (and maintenance?) process. I've seen the misconception that testing of software just means testing by users so they can decide if they should buy or more widely apply the software for their needs. (Quote: _Let's first finish coding. Then we can find people who test this._)

> Common methods / SE Methods
> Automated Test
> Oracle Test/ Lookup check
> Unit Test
> Integration Testing
> Metamorphic Testing
> Transition to hands-on part

The rest looks fine.

**Comment by Dilipjh** [comment]
> > Testing - What for?
> > What is testing?

Under this section do we introduce the common nomenclature in Software testing? as part of the theory session. 
I think this will help the attendees get a better structure of the testing approaches and divisions.

We should also highlight that testing need not be considered separate from the development process but is an integral part of an efficient development process.

- Should we mention that testing activities start with the definition of the requirements?
- should we mention inculcating good coding practices is the first step to better testing capabilities?
- Do we specify debugging tools? expand on how some testing tools help to debug?

> 
> In the upper two points, it's important to make sure that this is mostly about testing as part of the development (and maintenance?) process. 

This is mostly from the perspective of product development. (Developers/coders)

>I've seen the misconception that testing of software just means testing by users so they can decide if they should buy or more widely apply the software for their needs. 

This is mostly from the perspective of an end-user (company) accepting the software product.

> (Quote: _Let's first finish coding. Then we can find people who test this._)

This is when the development is done without the involvement of the QA team in the development cycle (usually an old software development model)

> > Common methods / SE Methods

Should we also mention the different ways in which the testing approach is categorized under this section? 
And then focus on function testing as it is most relevant to us.

> > Automated Test

We define and list the advance of the automated testing in the theory session. 
Does this translate to helping the attendees with setting up a simple basic automated test suit?

> > Oracle Test/ Lookup check
> > Unit Test
> > Integration Testing
> > Metamorphic Testing(MT) -

I can take up this part in theory.  I am hoping to set up a simple python MT example based on the available intro lessons (need to look at existing material and work on this)

> > Transition to hands-on part

**Comment by Dilipjh** [comment]
Do we have/select a common template for developing the slides?  it will facilitate parallel development.
I have made a few points and would like to start putting them into slides. it will help us review them during our next meet.

**Comment by fp21** [comment]
> Should we also mention the different ways in which the testing approach is categorized under this section?
> And then focus on function testing as it is most relevant to us.

I think we should do that.

> 
> 
>We define and list the advance of the automated testing in the theory session.
>Does this translate to helping the attendees with setting up a simple basic automated test suit?

Yes that is my idea.

> 
> 
> Do we have/select a common template for developing the slides? it will facilitate parallel development.
> I have made a few points and would like to start putting them into slides. it will help us review them during our next meet.

Think that's a good idea. I setup a initial latex template last week but had no internet access to upload it. It's now under slides.

**Comment by willirath** [comment]
- verification vs validation

**Comment by willirath** [comment]
- coverage

**Comment by willirath** [comment]
- failing test don't necessarily mean invalidation

**Comment by fp21** [comment]
I added the latex files under notes. I'll post a note when I finished the first 31.

**Comment by fp21** [comment]
I translated the first 32 slides and restructured them in the notes section.

**Comment by willirath** [comment]
> I translated the first 32 slides and restructured them in the notes section.

Structure looks good. I've used it for my translations as well (See #4.)

I'll have a look at the text soon.

**Comment by fp21** [comment]
- [x] translation review
- [x] note build
- [ ] slide build

**Comment by fp21** [comment]
The notes are done. Do we want to split the slides up, so that everyone build his own or do we want to build one presentation and everyone presents a part?

**Comment by Dilipjh** [comment]
> The notes are done. Do we want to split the slides up, so that everyone build his own or do we want to build one presentation and everyone presents a part?

I would prefer building one presentation and all of us just using it.

**Comment by fp21** [comment]
- Lecture (60min)@eprigge
  - Intro (10min)@sgu
    - What is Software Testing? (2min)@sgu
      - Definition (Myers,IEEE)
      - Techniques (Static, Dynamic)
      - Approaches (Unit,Integration,Regression,Methamorpic)
    - Common Testing Terms (2min)@sgu
      - Test cases
      - Test procedure
      - Test Data
      - Expected results
      - Test script
    - Fundamental Test Process (2min)@sgu
      - Test Flow Graph (Test driven Development)
    - Testing Activities (2min)@sgu
      - Test Planning
      - Test Design
      - Test Implementation
      - Test Evaluation
      - Test Closure
    - Test coverage (2min)@sgu
      - Exhaustive testing
      - Risk mitigation
      - Automation
      - Boundary Value Analysis
      - Equivalence Class Partitioning
  - Technique (50min)@wrath
    - Whitebox & Blackbox Testing (10min)@wrath
      - White-box Testing of Modules
      - Black Box Testing of modules
      - Black Box Test methods
    - Mocking (10min)@wrath
      - Categories
      - Summary
      - skipp JUnit examples
    - Unit Test (10min)@wrath
      - Automated
      - lowest level component testing
    - Integration Testing (10min)@dilipjh
      - top-down
      - bottom-up
      - big bang
    - Metamorphic Testing (10min)@dilipjh

**Comment by wrath** [comment]
Do i know this project ?

**Comment by willirath** [comment]
> Do i know this project ?

No, sorry for accidentally pinging you. I guess my handle @willirath was mistyped.
