### ISSUE TITLE
Metamorphic testing

### ISSUE THREAD

**Issue by willirath** [mardatade/Course-Software-Testing#5]
Image: https://www.mardata.de/fileadmin/user_upload/claus_hasselbring.png

contents:
- use _known_ symmetries / invariance of a software for verification
- useful if the "correct" results cannot be known (no oracle)
- test for known changes (or the known absence of changes) under changed inputs
- examples:
  - periodicity (see hands on)
  - invariance against shuffling input arguments

**Comment by Dilipjh** [comment]
Added the Metamorphic testing slide to Notes

Explained Metamorphic testing in a few words 
added image finalized
Listed a few usual functions that are explored as metamorphic relations
